azure:
  application-insights: 
    instrumentation-key: 3b5bd424-f2d9-4011-a34b-279b06833155
spring:
  main:
    banner-mode: "console"
  application:
    name: app-aqua-plus-api
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://bd-aqua-plus.postgres.database.azure.com:5432/aquaplus
    username: aquaPlus
    password: ji62inmB2Ps5L4zcJE84lw==
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariPoolAquaPlus
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      format-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
mail:
  host: smtp.gmail.com 
  port: 587             
  username: info@aquaplus.dev
  password: i3lr9ve662SlYUHRuNGJpaan4Eyk3jfZ
  properties:
    mail:
      smtp:
       auth: true
       starttls:
         enable: true
         required: true  
seguridad:
  llave: keyaquaplus
link:
  recover: https://aquaplus.dev/auth/recover-password?token=
app:
  cors:
    - http://localhost:4200
    - https://aquaplus.dev
