name: Build and deploy JAR app to Azure Web App - app-aqua-plus-api-test

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      actions: write   # necesario para limpiar artifacts

    steps:
      # Limpieza automática de artifacts viejos
      - name: Cleanup old artifacts
        uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 1days
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
          cache: maven   # acelera build y reduce uso de storage

      - name: Configure Maven settings for GitHub Packages
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>github</id>
                <username>CodeMakers-dev</username>
                <password>${{ secrets.TOKEN_LIB_AQUA }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Build project
        run: mvn -B clean package -DskipTests

      - name: Verify JAR exists
        run: |
          echo "Contenido de target:"
          ls -lh target/

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CCDAD8596A384C279208F464E847227D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F06F5144686A486E9B4969D95899E166 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_27BA111081574C95B6AFB2403A1BBF07 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-aqua-plus-api-test'
          slot-name: 'Production'
          package: target/*.jar
