name: Build and deploy JAR app to Azure Web App - app-aqua-plus-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read   # Necesario para actions/checkout
      packages: read   # Necesario para descargar dependencias de GitHub Packages

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Configure Maven settings for GitHub Packages
        run: |
          mkdir -p ~/.m2
          echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>github</id>
                <username>${{github.actor}}</username>
                <password>${{secrets.TOKEN_LIB_AQUA}}</password>
              </server>
            </servers>
          </settings>' > ~/.m2/settings.xml

      - name: Build with Maven
        run: mvn -B clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write   # Necesario para OIDC con Azure
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8F6892A24539449DA2E1024630AD7CC9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_96500EE46D4C44509095C7C982E45537 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E3EC9B842DEB4722876474713503B1C8 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-aqua-plus-api'
          slot-name: 'Production'
          package: '*.jar'

